src/Entity/ServerInstance.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\IdTrait;
use App\Entity\Trait\UpdatedAtTrait;
use App\Repository\ServerInstanceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ServerInstanceRepository::class)]
#[ORM\HasLifecycleCallbacks]
class ServerInstance
{
    use IdTrait, CreatedAtTrait, UpdatedAtTrait;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 3, max: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 32, nullable: true)]
    #[Assert\Length(min: 12, max: 32)]
    private ?string $baseUrl = null;

    /**
     * @var Collection<int, Crawling>
     */
    #[ORM\OneToMany(targetEntity: Crawling::class, mappedBy: 'serverInstance', orphanRemoval: true)]
    private Collection $crawlings;

    #[ORM\Column(length: 20)]
    private ?string $status = null;

    public function __construct()
    {
        $this->crawlings = new ArrayCollection();
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getBaseUrl(): ?string
    {
        return $this->baseUrl;
    }

    public function setBaseUrl(?string $baseUrl): static
    {
        $this->baseUrl = $baseUrl;

        return $this;
    }

    /**
     * @return Collection<int, Crawling>
     */
    public function getCrawlings(): Collection
    {
        return $this->crawlings;
    }

    public function getCrawlingCount(): int
    {
        return $this->crawlings->count();
    }

    public function addCrawling(Crawling $crawling): static
    {
        if (!$this->crawlings->contains($crawling)) {
            $this->crawlings->add($crawling);
            $crawling->setServerInstance($this);
        }

        return $this;
    }

    public function removeCrawling(Crawling $crawling): static
    {
        if ($this->crawlings->removeElement($crawling)) {
            // set the owning side to null (unless already changed)
            if ($crawling->getServerInstance() === $this) {
                $crawling->setServerInstance(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/ServerInstanceType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\ServerInstance;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ServerInstanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Name des Servers',
                'help' => 'Der interne Name des Servers',
            ])
            ->add('baseUrl', UrlType::class, [
                'label' => 'Base-Url',
                'required' => false,
                'help' => 'Die URL zum Server',
                'default_protocol' => 'https',
            ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ServerInstance::class,
        ]);
    }
}

src/Controller/ServerInstanceController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\ServerInstance;
use App\Event\ServerInstanceToDeleteEvent;
use App\Factory\ServerInstanceFactory;
use App\Form\ServerInstanceType;
use App\Repository\ServerInstanceRepository;
use App\Security\Voter\ServerInstanceVoter;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityNotFoundException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Workflow\WorkflowInterface;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;

#[Route(path: '/server-instance', name: 'app_server_instance_')]
class ServerInstanceController extends AbstractController
{
    public function __construct(
        protected readonly EntityManagerInterface   $entityManager,
        protected readonly ServerInstanceRepository $serverInstanceRepository
    )
    {
    }

    #[Route(path: '/list', name: 'list', methods: ['GET'])]
    public function list(): Response
    {
        return $this->render('server-instance/list.html.twig', [
            'instances' => $this->serverInstanceRepository->findActive(),
        ]);
    }

    #[Route(path: '/create', name: 'create', methods: ['GET', 'POST'])]
    public function create(Request $request, ServerInstanceFactory $factory): Response
    {
        $form = $this->createForm(ServerInstanceType::class, $factory->createInstance());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($form->getData());
            $this->entityManager->flush();

            $this->addFlash('success', 'Server-Instanz wurde erfolgreich angelegt.');

            return $this->redirectToRoute('app_server_instance_list');
        }

        return $this->render('server-instance/create.html.twig', [
            'serverInstanceForm' => $form,
        ]);
    }

    #[Route(path: '/{id}', name: 'read', methods: ['GET'])]
    public function read(int $id): Response
    {
        $serverInstance = $this->serverInstanceRepository->find($id);

        $this->denyAccessUnlessGranted(ServerInstanceVoter::VIEW, $serverInstance);

        if (!$serverInstance instanceof ServerInstance) {
            throw new EntityNotFoundException();
        }

        return $this->render('server-instance/read.html.twig', [
            'serverInstance' => $serverInstance,
        ]);
    }

    #[Route(path: '/update/{id}', name: 'update', methods: ['GET', 'POST'])]
    public function update(int $id, Request $request): Response
    {
        $serverInstance = $this->serverInstanceRepository->find($id);

        $form = $this->createForm(ServerInstanceType::class, $serverInstance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            $this->addFlash('success', 'Server-Instanz wurde erfolgreich bearbeitet.');
        }

        return $this->render('server-instance/update.html.twig', [
            'serverInstanceForm' => $form,
        ]);
    }

    #[Route(path: '/delete/{id}', name: 'delete', methods: ['GET'])]
    public function delete(
        int                      $id,
        EventDispatcherInterface $eventDispatcher
    ): Response
    {
        $serverInstance = $this->serverInstanceRepository->find($id);

        $event = new ServerInstanceToDeleteEvent($serverInstance);
        $eventDispatcher->dispatch($event, $event::NAME);

        if($event->isTransitionSuccessful()) {
            $this->addFlash('success', 'Server-Instanz wurde erfolgreich entfernt.');
            return $this->redirectToRoute('app_server_instance_list');
        } else {
            $this->addFlash('warning', 'Server-Instanz darf nicht gelöscht werden.');
            return $this->redirectToRoute('app_crawling_show', ['id' => $id]);
        }
    }
}

templates/server-instance/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-4">
    {{ form(serverInstanceForm) }}
    </div>
</div>
{% endblock %}

templates/server-instance/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-8">
            <h2>Server Instanzen</h2>

            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Base-Url</th>
                    <th>Anzahl der Crawlings</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for instance in instances %}
                    <tr>
                        <td>{{ instance.name }}</td>
                        <td>{% if instance.baseUrl %}<a href="{{ instance.baseUrl }}" target="_blank">{{ instance.baseUrl }}</a> {% endif %}</td>
                        <td>{{ instance.crawlingCount }}</td>
                        <td class="text-end">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                Aktionen
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item"
                                       href="{{ path('app_server_instance_update', {id: instance.id}) }}">Bearbeiten</a>
                                </li>
                                <li><a class="dropdown-item"
                                       href="{{ path('app_server_instance_read', {id: instance.id}) }}">Detailansicht</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item"
                                       href="{{ path('app_server_instance_delete', {id: instance.id}) }}"
                                       onclick="return confirm('Soll diese Server Instanz wirklich gelöscht werden?')">Löschen</a>
                                </li>
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/server-instance/read.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-4">
            <a href="{{ path('app_server_instance_list') }}" class="my-3">Zurück zur Liste</a>
            <h2 class="my-5">Server Instanz Details</h2>
            <dl class="row">
                <dt>Name</dt>
                <dd>{{ serverInstance.name }}</dd>
                <dt>Base-Url</dt>
                <dd>{% if serverInstance.baseUrl %}<a href="{{ serverInstance.baseUrl }}" target="_blank">{{ serverInstance.baseUrl }}</a> {% endif %}</dd>
                <dt>Aktualisiert am</dt>
                <dd>{% if serverInstance.updatedAt %}{{ serverInstance.updatedAt|date('H:i:s d.m.Y') }}{% else %}Noch nie aktualisiert{% endif %}</dd>
                <dt>Erstellt am</dt>
                <dd>{{ serverInstance.createdAt|date('H:i:s d.m.Y') }}</dd>
            </dl>
            <hr />
            <div class="row justify-content-center">
                <div class="col">
                    <a href="{{ path('app_server_instance_update', {id: serverInstance.id}) }}" class="btn btn-sm btn-outline-dark">Edit</a>
                </div>
                <div class="col">
                    <a href="{{ path('app_server_instance_delete', {id: serverInstance.id}) }}" class="btn btn-sm btn-outline-danger" onclick="return confirm('Soll diese Server Instanz wirklich gelöscht werden?')">Löschen</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/server-instance/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-4">
            <a href="{{ path('app_server_instance_list') }}">zurück zur Liste</a>
            <h2 class="my-5">Server Instanz bearbeiten</h2>
            {{ form(serverInstanceForm) }}
        </div>
    </div>
{% endblock %}